### ISSUE TITLE
Items not outputing to interface p2p's

### ISSUE THREAD

**Issue by Adix1120** [AE2-UEL/NAE2#64] opened 2024-05-15 21:58 UTC
When I setup ender io machines with interface p2p's, for example soul binder or slice'n'splice all is going smoothly until it is supposed to output content back to ae, I have to wait around 5-6 minutes for items to output, but this only happened when I first set uped my machines, second time it was all good and it outputed items normally. 
![2024-05-15_23 26 36](https://github.com/AE2-UEL/NAE2/assets/169950368/0f28424d-6b68-4c9f-be5c-0010aeba68d9)

**Comment by NotMyWing** [comment] 2024-05-16 05:17
Unfortunately can't reproduce. 

This may be caused by EnderIO first checking the tunnels, realizing it can't output and not re-checking ever again. I'll leave this open for now, if this issue happens again, feel free to respond with more information.

**Comment by NotMyWing** [comment] 2024-06-18 07:40
Should be fixed in c991997cfa5526b4cfbb3ad76fa288a32948809c.

**Closed by NotMyWing** 2024-06-18 07:40 UTC
Labels: question
